---

- name: install rpm packages
  dnf:
    name:
      - pam-u2f
      - pamu2fcfg
    state: latest

# - name: Copy a pam cofig
#   copy:
#     src: ./files/pam_yubico_u2f
#     dest: ~/.config/Yubico/u2f_keys
#     mode: '0644'

- name: Copy gdm config
  copy:
    src: ./files/pam_yubico_u2f_gdm
    dest: /etc/pam.d/gdm-password
    owner: root
    group: root
    backup: 'yes'
    mode: 'u=rw,g=r,o=r'
    
- name: Copy sudo config
  copy:
    src: ./files/pam_yubico_u2f_sudo
    dest: /etc/pam.d/sudo
    owner: root
    group: root
    backup: 'yes'
    mode: 'u=rw,g=r,o=r'

...